### ISSUE TITLE
latest release v1.0.1 misses dependencies

### ISSUE THREAD

**Issue by eburi** [gdi2290/angular-password#10]
Hi,

could you release a new version with the proper dependencies? Looks like bower.json and package.json on master were fixed, but the latest version (referred by the tag v1.0.1) does not include the angular dependency in bower.json, yet.

BR
Erich

**Comment by gdi2290** [comment]
can you make a pull-request?

**Comment by eburi** [comment]
Hi,
Last commit on master: 570f28d  
Latest npm release version: v1.0.1 has commit (referred to by tag): 5282b27

there is no need for a PR. All I'm asking for is a new release - maybe v1.0.2 - that contains the current state of master and it's all done.

BR
Erich

**Comment by eburi** [comment]
Hi, 
I'll try another way to show the problem. 

v1.0.1 package.json: https://github.com/gdi2290/angular-password/blob/v1.0.1/package.json
v1.0.1 bower.json: https://github.com/gdi2290/angular-password/blob/v1.0.1/bower.json

both files have NO dependencies-section.


master package.json: https://github.com/gdi2290/angular-password/blob/master/package.json
master bower.json: https://github.com/gdi2290/angular-password/blob/master/bower.json

both files DO have dependency-information!


Therefore I'm asking only for a new release on bower and npm.

Thanks,
Erich

**Comment by gdi2290** [comment]
ok sorry about that. I pushed up published and cut a tag for 1.0.3
