### ISSUE TITLE
wrong dependencies in package.json?

### ISSUE THREAD

**Issue by SlippySken** [gdi2290/angular-password#12]
Hello :),

maybe I'm wrong, but I think these dependencies
    "angular-mocks": "^1.5.5",
    "gulp": "^3.9.1",
    "gulp-jshint": "^2.0.0",
    "gulp-rename": "^1.2.2",
    "gulp-uglify": "^1.5.3",
    "jasmine-core": "^2.4.1",
    "jshint": "^2.9.2",
    "karma": "^0.13.22",
    "karma-jasmine": "^0.3.8",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-spec-reporter": "0.0.26",
    "phantomjs-prebuilt": "^2.1.7"

should be devDependencies because only angular is needed. Jspm fails with some fetching errors because it tries to fetch all dependencies, which aren't used at runtime :).

**Comment by christianbundy** [comment]
Man, I was wondering why my `npm install` was taking so long -- these should 100% be moved to `devDependencies`.
